/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param token JWT access token
 * @param expiresIn Token TTL in seconds (handler currently hard-codes 3600)
 */
@Serializable

data class AuthResponse (

    /* JWT access token */
    @SerialName(value = "token")
    val token: kotlin.String,

    /* Token TTL in seconds (handler currently hard-codes 3600) */
    @SerialName(value = "expires_in")
    val expiresIn: kotlin.Int

) {


}

