/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param accountId 
 * @param balance Balance formatted as string (decimal.Decimal.String()).
 * @param currency 
 */
@Serializable

data class BalanceResponse (

    @Contextual @SerialName(value = "account_id")
    val accountId: java.util.UUID,

    /* Balance formatted as string (decimal.Decimal.String()). */
    @SerialName(value = "balance")
    val balance: kotlin.String,

    @SerialName(value = "currency")
    val currency: kotlin.String

) {


}

