/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param amount Decimal encoded as string (shopspring/decimal)
 * @param type 
 * @param description 
 */
@Serializable

data class CreateMovementRequest (

    /* Decimal encoded as string (shopspring/decimal) */
    @SerialName(value = "amount")
    val amount: kotlin.String,

    @SerialName(value = "type")
    val type: CreateMovementRequest.Type,

    @SerialName(value = "description")
    val description: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: credit,debit
     */
    @Serializable
    enum class Type(val value: kotlin.String) {
        @SerialName(value = "credit") credit("credit"),
        @SerialName(value = "debit") debit("debit");
    }

}

