/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.APIError

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Current error envelope from `internal/util/errors.go`. Note: for non-*util.APIError errors, the server responds with code=500 and message=\"internal server error\". 
 *
 * @param error 
 */
@Serializable

data class ErrorResponse (

    @SerialName(value = "error")
    val error: APIError

) {


}

