/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Mirrors `internal/model.Movement` JSON. NOTE: in Go it serializes `amount` as decimal (shopspring/decimal) which is typically a JSON string/number depending on config. TODO: confirm runtime JSON encoding for decimal.Decimal and adjust if needed. 
 *
 * @param id 
 * @param accountId 
 * @param amount Decimal encoded as string (shopspring/decimal)
 * @param type 
 * @param description 
 * @param occurredAt 
 */
@Serializable

data class Movement (

    @SerialName(value = "id")
    val id: kotlin.Long,

    @Contextual @SerialName(value = "account_id")
    val accountId: java.util.UUID,

    /* Decimal encoded as string (shopspring/decimal) */
    @SerialName(value = "amount")
    val amount: kotlin.String,

    @SerialName(value = "type")
    val type: Movement.Type,

    @SerialName(value = "description")
    val description: kotlin.String,

    @Contextual @SerialName(value = "occurred_at")
    val occurredAt: java.time.OffsetDateTime

) {

    /**
     * 
     *
     * Values: credit,debit
     */
    @Serializable
    enum class Type(val value: kotlin.String) {
        @SerialName(value = "credit") credit("credit"),
        @SerialName(value = "debit") debit("debit");
    }

}

