/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param currentPage 
 * @param totalPages 
 * @param totalItems 
 * @param perPage 
 */
@Serializable

data class PaginationMeta (

    @SerialName(value = "current_page")
    val currentPage: kotlin.Int,

    @SerialName(value = "total_pages")
    val totalPages: kotlin.Int,

    @SerialName(value = "total_items")
    val totalItems: kotlin.Int,

    @SerialName(value = "per_page")
    val perPage: kotlin.Int

) {


}

