/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.PaginationMeta
import org.openapitools.client.models.Transfer

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Concrete shape of `util.PaginatedResponse` as returned by `TransferService.GetByAccountID()`. 
 *
 * @param `data` 
 * @param pagination 
 */
@Serializable

data class PaginatedTransfersResponse (

    @SerialName(value = "data")
    val `data`: kotlin.collections.List<Transfer>,

    @SerialName(value = "pagination")
    val pagination: PaginationMeta

) {


}

