/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param email 
 * @param password 
 * @param username 
 * @param firstName 
 * @param lastName 
 * @param fiscalCode 
 */
@Serializable

data class SignUpRequest (

    @SerialName(value = "email")
    val email: kotlin.String,

    @SerialName(value = "password")
    val password: kotlin.String,

    @SerialName(value = "username")
    val username: kotlin.String,

    @SerialName(value = "first_name")
    val firstName: kotlin.String,

    @SerialName(value = "last_name")
    val lastName: kotlin.String,

    @SerialName(value = "fiscal_code")
    val fiscalCode: kotlin.String

) {


}

