/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param fromAccount 
 * @param toAccount 
 * @param amount Decimal encoded as string (shopspring/decimal)
 * @param status 
 * @param initiatedAt 
 * @param completedAt 
 */
@Serializable

data class Transfer (

    @SerialName(value = "id")
    val id: kotlin.Long,

    @Contextual @SerialName(value = "from_account")
    val fromAccount: java.util.UUID,

    @Contextual @SerialName(value = "to_account")
    val toAccount: java.util.UUID,

    /* Decimal encoded as string (shopspring/decimal) */
    @SerialName(value = "amount")
    val amount: kotlin.String,

    @SerialName(value = "status")
    val status: Transfer.Status,

    @Contextual @SerialName(value = "initiated_at")
    val initiatedAt: java.time.OffsetDateTime,

    @Contextual @SerialName(value = "completed_at")
    val completedAt: java.time.OffsetDateTime?

) {

    /**
     * 
     *
     * Values: pending,completed,failed
     */
    @Serializable
    enum class Status(val value: kotlin.String) {
        @SerialName(value = "pending") pending("pending"),
        @SerialName(value = "completed") completed("completed"),
        @SerialName(value = "failed") failed("failed");
    }

}

