/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param toAccount 
 * @param amount Decimal encoded as string (shopspring/decimal)
 * @param description 
 */
@Serializable

data class TransferRequest (

    @Contextual @SerialName(value = "to_account")
    val toAccount: java.util.UUID,

    /* Decimal encoded as string (shopspring/decimal) */
    @SerialName(value = "amount")
    val amount: kotlin.String,

    @SerialName(value = "description")
    val description: kotlin.String? = null

) {


}

