/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param email 
 * @param username 
 * @param firstName 
 * @param lastName 
 * @param fiscalCode 
 * @param createdAt 
 * @param updatedAt 
 */
@Serializable

data class User (

    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    @SerialName(value = "email")
    val email: kotlin.String,

    @SerialName(value = "username")
    val username: kotlin.String,

    @SerialName(value = "first_name")
    val firstName: kotlin.String,

    @SerialName(value = "last_name")
    val lastName: kotlin.String,

    @SerialName(value = "fiscal_code")
    val fiscalCode: kotlin.String,

    @Contextual @SerialName(value = "created_at")
    val createdAt: java.time.OffsetDateTime,

    @Contextual @SerialName(value = "updated_at")
    val updatedAt: java.time.OffsetDateTime

) {


}

