/* tslint:disable */
/* eslint-disable */
/**
 * VDM2 Banking API
 * Baseline OpenAPI spec extracted from the existing Gin router/handlers. After this initial extraction, this OpenAPI contract becomes the source of truth. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface APIError
 */
export interface APIError {
    /**
     * 
     * @type {number}
     * @memberof APIError
     */
    code: number;
    /**
     * 
     * @type {string}
     * @memberof APIError
     */
    message: string;
}

/**
 * Check if a given object implements the APIError interface.
 */
export function instanceOfAPIError(value: object): value is APIError {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function APIErrorFromJSON(json: any): APIError {
    return APIErrorFromJSONTyped(json, false);
}

export function APIErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): APIError {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'message': json['message'],
    };
}

export function APIErrorToJSON(json: any): APIError {
    return APIErrorToJSONTyped(json, false);
}

export function APIErrorToJSONTyped(value?: APIError | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
    };
}

