/* tslint:disable */
/* eslint-disable */
/**
 * VDM2 Banking API
 * Baseline OpenAPI spec extracted from the existing Gin router/handlers. After this initial extraction, this OpenAPI contract becomes the source of truth. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthResponse
 */
export interface AuthResponse {
    /**
     * JWT access token
     * @type {string}
     * @memberof AuthResponse
     */
    token: string;
    /**
     * Token TTL in seconds (handler currently hard-codes 3600)
     * @type {number}
     * @memberof AuthResponse
     */
    expiresIn: number;
}

/**
 * Check if a given object implements the AuthResponse interface.
 */
export function instanceOfAuthResponse(value: object): value is AuthResponse {
    if (!('token' in value) || value['token'] === undefined) return false;
    if (!('expiresIn' in value) || value['expiresIn'] === undefined) return false;
    return true;
}

export function AuthResponseFromJSON(json: any): AuthResponse {
    return AuthResponseFromJSONTyped(json, false);
}

export function AuthResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'token': json['token'],
        'expiresIn': json['expires_in'],
    };
}

export function AuthResponseToJSON(json: any): AuthResponse {
    return AuthResponseToJSONTyped(json, false);
}

export function AuthResponseToJSONTyped(value?: AuthResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'token': value['token'],
        'expires_in': value['expiresIn'],
    };
}

