/* tslint:disable */
/* eslint-disable */
/**
 * VDM2 Banking API
 * Baseline OpenAPI spec extracted from the existing Gin router/handlers. After this initial extraction, this OpenAPI contract becomes the source of truth. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BalanceResponse
 */
export interface BalanceResponse {
    /**
     * 
     * @type {string}
     * @memberof BalanceResponse
     */
    accountId: string;
    /**
     * Balance formatted as string (decimal.Decimal.String()).
     * @type {string}
     * @memberof BalanceResponse
     */
    balance: string;
    /**
     * 
     * @type {string}
     * @memberof BalanceResponse
     */
    currency: string;
}

/**
 * Check if a given object implements the BalanceResponse interface.
 */
export function instanceOfBalanceResponse(value: object): value is BalanceResponse {
    if (!('accountId' in value) || value['accountId'] === undefined) return false;
    if (!('balance' in value) || value['balance'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    return true;
}

export function BalanceResponseFromJSON(json: any): BalanceResponse {
    return BalanceResponseFromJSONTyped(json, false);
}

export function BalanceResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BalanceResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'accountId': json['account_id'],
        'balance': json['balance'],
        'currency': json['currency'],
    };
}

export function BalanceResponseToJSON(json: any): BalanceResponse {
    return BalanceResponseToJSONTyped(json, false);
}

export function BalanceResponseToJSONTyped(value?: BalanceResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'account_id': value['accountId'],
        'balance': value['balance'],
        'currency': value['currency'],
    };
}

