/* tslint:disable */
/* eslint-disable */
/**
 * VDM2 Banking API
 * Baseline OpenAPI spec extracted from the existing Gin router/handlers. After this initial extraction, this OpenAPI contract becomes the source of truth. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateMovementRequest
 */
export interface CreateMovementRequest {
    /**
     * Decimal encoded as string (shopspring/decimal)
     * @type {string}
     * @memberof CreateMovementRequest
     */
    amount: string;
    /**
     * 
     * @type {string}
     * @memberof CreateMovementRequest
     */
    type: CreateMovementRequestTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof CreateMovementRequest
     */
    description?: string;
}


/**
 * @export
 */
export const CreateMovementRequestTypeEnum = {
    Credit: 'credit',
    Debit: 'debit'
} as const;
export type CreateMovementRequestTypeEnum = typeof CreateMovementRequestTypeEnum[keyof typeof CreateMovementRequestTypeEnum];


/**
 * Check if a given object implements the CreateMovementRequest interface.
 */
export function instanceOfCreateMovementRequest(value: object): value is CreateMovementRequest {
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function CreateMovementRequestFromJSON(json: any): CreateMovementRequest {
    return CreateMovementRequestFromJSONTyped(json, false);
}

export function CreateMovementRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateMovementRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'],
        'type': json['type'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function CreateMovementRequestToJSON(json: any): CreateMovementRequest {
    return CreateMovementRequestToJSONTyped(json, false);
}

export function CreateMovementRequestToJSONTyped(value?: CreateMovementRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount': value['amount'],
        'type': value['type'],
        'description': value['description'],
    };
}

