/* tslint:disable */
/* eslint-disable */
/**
 * VDM2 Banking API
 * Baseline OpenAPI spec extracted from the existing Gin router/handlers. After this initial extraction, this OpenAPI contract becomes the source of truth. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Mirrors `internal/model.Movement` JSON.
 * NOTE: in Go it serializes `amount` as decimal (shopspring/decimal) which is typically a JSON string/number depending on config.
 * TODO: confirm runtime JSON encoding for decimal.Decimal and adjust if needed.
 * 
 * @export
 * @interface Movement
 */
export interface Movement {
    /**
     * 
     * @type {number}
     * @memberof Movement
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof Movement
     */
    accountId: string;
    /**
     * Decimal encoded as string (shopspring/decimal)
     * @type {string}
     * @memberof Movement
     */
    amount: string;
    /**
     * 
     * @type {string}
     * @memberof Movement
     */
    type: MovementTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof Movement
     */
    description: string;
    /**
     * 
     * @type {Date}
     * @memberof Movement
     */
    occurredAt: Date;
}


/**
 * @export
 */
export const MovementTypeEnum = {
    Credit: 'credit',
    Debit: 'debit'
} as const;
export type MovementTypeEnum = typeof MovementTypeEnum[keyof typeof MovementTypeEnum];


/**
 * Check if a given object implements the Movement interface.
 */
export function instanceOfMovement(value: object): value is Movement {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('accountId' in value) || value['accountId'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('occurredAt' in value) || value['occurredAt'] === undefined) return false;
    return true;
}

export function MovementFromJSON(json: any): Movement {
    return MovementFromJSONTyped(json, false);
}

export function MovementFromJSONTyped(json: any, ignoreDiscriminator: boolean): Movement {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'accountId': json['account_id'],
        'amount': json['amount'],
        'type': json['type'],
        'description': json['description'],
        'occurredAt': (new Date(json['occurred_at'])),
    };
}

export function MovementToJSON(json: any): Movement {
    return MovementToJSONTyped(json, false);
}

export function MovementToJSONTyped(value?: Movement | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'account_id': value['accountId'],
        'amount': value['amount'],
        'type': value['type'],
        'description': value['description'],
        'occurred_at': value['occurredAt'].toISOString(),
    };
}

