/* tslint:disable */
/* eslint-disable */
/**
 * VDM2 Banking API
 * Baseline OpenAPI spec extracted from the existing Gin router/handlers. After this initial extraction, this OpenAPI contract becomes the source of truth. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Movement } from './Movement';
import {
    MovementFromJSON,
    MovementFromJSONTyped,
    MovementToJSON,
    MovementToJSONTyped,
} from './Movement';
import type { PaginationMeta } from './PaginationMeta';
import {
    PaginationMetaFromJSON,
    PaginationMetaFromJSONTyped,
    PaginationMetaToJSON,
    PaginationMetaToJSONTyped,
} from './PaginationMeta';

/**
 * Concrete shape of `util.PaginatedResponse` as returned by `MovementService.GetByAccountID()`.
 * 
 * @export
 * @interface PaginatedMovementsResponse
 */
export interface PaginatedMovementsResponse {
    /**
     * 
     * @type {Array<Movement>}
     * @memberof PaginatedMovementsResponse
     */
    data: Array<Movement>;
    /**
     * 
     * @type {PaginationMeta}
     * @memberof PaginatedMovementsResponse
     */
    pagination: PaginationMeta;
}

/**
 * Check if a given object implements the PaginatedMovementsResponse interface.
 */
export function instanceOfPaginatedMovementsResponse(value: object): value is PaginatedMovementsResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('pagination' in value) || value['pagination'] === undefined) return false;
    return true;
}

export function PaginatedMovementsResponseFromJSON(json: any): PaginatedMovementsResponse {
    return PaginatedMovementsResponseFromJSONTyped(json, false);
}

export function PaginatedMovementsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedMovementsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(MovementFromJSON)),
        'pagination': PaginationMetaFromJSON(json['pagination']),
    };
}

export function PaginatedMovementsResponseToJSON(json: any): PaginatedMovementsResponse {
    return PaginatedMovementsResponseToJSONTyped(json, false);
}

export function PaginatedMovementsResponseToJSONTyped(value?: PaginatedMovementsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(MovementToJSON)),
        'pagination': PaginationMetaToJSON(value['pagination']),
    };
}

