/* tslint:disable */
/* eslint-disable */
/**
 * VDM2 Banking API
 * Baseline OpenAPI spec extracted from the existing Gin router/handlers. After this initial extraction, this OpenAPI contract becomes the source of truth. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaginationMeta } from './PaginationMeta';
import {
    PaginationMetaFromJSON,
    PaginationMetaFromJSONTyped,
    PaginationMetaToJSON,
    PaginationMetaToJSONTyped,
} from './PaginationMeta';
import type { Transfer } from './Transfer';
import {
    TransferFromJSON,
    TransferFromJSONTyped,
    TransferToJSON,
    TransferToJSONTyped,
} from './Transfer';

/**
 * Concrete shape of `util.PaginatedResponse` as returned by `TransferService.GetByAccountID()`.
 * 
 * @export
 * @interface PaginatedTransfersResponse
 */
export interface PaginatedTransfersResponse {
    /**
     * 
     * @type {Array<Transfer>}
     * @memberof PaginatedTransfersResponse
     */
    data: Array<Transfer>;
    /**
     * 
     * @type {PaginationMeta}
     * @memberof PaginatedTransfersResponse
     */
    pagination: PaginationMeta;
}

/**
 * Check if a given object implements the PaginatedTransfersResponse interface.
 */
export function instanceOfPaginatedTransfersResponse(value: object): value is PaginatedTransfersResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('pagination' in value) || value['pagination'] === undefined) return false;
    return true;
}

export function PaginatedTransfersResponseFromJSON(json: any): PaginatedTransfersResponse {
    return PaginatedTransfersResponseFromJSONTyped(json, false);
}

export function PaginatedTransfersResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedTransfersResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(TransferFromJSON)),
        'pagination': PaginationMetaFromJSON(json['pagination']),
    };
}

export function PaginatedTransfersResponseToJSON(json: any): PaginatedTransfersResponse {
    return PaginatedTransfersResponseToJSONTyped(json, false);
}

export function PaginatedTransfersResponseToJSONTyped(value?: PaginatedTransfersResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(TransferToJSON)),
        'pagination': PaginationMetaToJSON(value['pagination']),
    };
}

