/* tslint:disable */
/* eslint-disable */
/**
 * VDM2 Banking API
 * Baseline OpenAPI spec extracted from the existing Gin router/handlers. After this initial extraction, this OpenAPI contract becomes the source of truth. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PaginationMeta
 */
export interface PaginationMeta {
    /**
     * 
     * @type {number}
     * @memberof PaginationMeta
     */
    currentPage: number;
    /**
     * 
     * @type {number}
     * @memberof PaginationMeta
     */
    totalPages: number;
    /**
     * 
     * @type {number}
     * @memberof PaginationMeta
     */
    totalItems: number;
    /**
     * 
     * @type {number}
     * @memberof PaginationMeta
     */
    perPage: number;
}

/**
 * Check if a given object implements the PaginationMeta interface.
 */
export function instanceOfPaginationMeta(value: object): value is PaginationMeta {
    if (!('currentPage' in value) || value['currentPage'] === undefined) return false;
    if (!('totalPages' in value) || value['totalPages'] === undefined) return false;
    if (!('totalItems' in value) || value['totalItems'] === undefined) return false;
    if (!('perPage' in value) || value['perPage'] === undefined) return false;
    return true;
}

export function PaginationMetaFromJSON(json: any): PaginationMeta {
    return PaginationMetaFromJSONTyped(json, false);
}

export function PaginationMetaFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginationMeta {
    if (json == null) {
        return json;
    }
    return {
        
        'currentPage': json['current_page'],
        'totalPages': json['total_pages'],
        'totalItems': json['total_items'],
        'perPage': json['per_page'],
    };
}

export function PaginationMetaToJSON(json: any): PaginationMeta {
    return PaginationMetaToJSONTyped(json, false);
}

export function PaginationMetaToJSONTyped(value?: PaginationMeta | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'current_page': value['currentPage'],
        'total_pages': value['totalPages'],
        'total_items': value['totalItems'],
        'per_page': value['perPage'],
    };
}

