/* tslint:disable */
/* eslint-disable */
/**
 * VDM2 Banking API
 * Baseline OpenAPI spec extracted from the existing Gin router/handlers. After this initial extraction, this OpenAPI contract becomes the source of truth. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Transfer
 */
export interface Transfer {
    /**
     * 
     * @type {number}
     * @memberof Transfer
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof Transfer
     */
    fromAccount: string;
    /**
     * 
     * @type {string}
     * @memberof Transfer
     */
    toAccount: string;
    /**
     * Decimal encoded as string (shopspring/decimal)
     * @type {string}
     * @memberof Transfer
     */
    amount: string;
    /**
     * 
     * @type {string}
     * @memberof Transfer
     */
    status: TransferStatusEnum;
    /**
     * 
     * @type {Date}
     * @memberof Transfer
     */
    initiatedAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof Transfer
     */
    completedAt: Date | null;
}


/**
 * @export
 */
export const TransferStatusEnum = {
    Pending: 'pending',
    Completed: 'completed',
    Failed: 'failed'
} as const;
export type TransferStatusEnum = typeof TransferStatusEnum[keyof typeof TransferStatusEnum];


/**
 * Check if a given object implements the Transfer interface.
 */
export function instanceOfTransfer(value: object): value is Transfer {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('fromAccount' in value) || value['fromAccount'] === undefined) return false;
    if (!('toAccount' in value) || value['toAccount'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('initiatedAt' in value) || value['initiatedAt'] === undefined) return false;
    if (!('completedAt' in value) || value['completedAt'] === undefined) return false;
    return true;
}

export function TransferFromJSON(json: any): Transfer {
    return TransferFromJSONTyped(json, false);
}

export function TransferFromJSONTyped(json: any, ignoreDiscriminator: boolean): Transfer {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'fromAccount': json['from_account'],
        'toAccount': json['to_account'],
        'amount': json['amount'],
        'status': json['status'],
        'initiatedAt': (new Date(json['initiated_at'])),
        'completedAt': (json['completed_at'] == null ? null : new Date(json['completed_at'])),
    };
}

export function TransferToJSON(json: any): Transfer {
    return TransferToJSONTyped(json, false);
}

export function TransferToJSONTyped(value?: Transfer | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'from_account': value['fromAccount'],
        'to_account': value['toAccount'],
        'amount': value['amount'],
        'status': value['status'],
        'initiated_at': value['initiatedAt'].toISOString(),
        'completed_at': value['completedAt'] == null ? value['completedAt'] : value['completedAt'].toISOString(),
    };
}

