/* tslint:disable */
/* eslint-disable */
/**
 * VDM2 Banking API
 * Baseline OpenAPI spec extracted from the existing Gin router/handlers. After this initial extraction, this OpenAPI contract becomes the source of truth. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TransferRequest
 */
export interface TransferRequest {
    /**
     * 
     * @type {string}
     * @memberof TransferRequest
     */
    toAccount: string;
    /**
     * Decimal encoded as string (shopspring/decimal)
     * @type {string}
     * @memberof TransferRequest
     */
    amount: string;
    /**
     * 
     * @type {string}
     * @memberof TransferRequest
     */
    description?: string;
}

/**
 * Check if a given object implements the TransferRequest interface.
 */
export function instanceOfTransferRequest(value: object): value is TransferRequest {
    if (!('toAccount' in value) || value['toAccount'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    return true;
}

export function TransferRequestFromJSON(json: any): TransferRequest {
    return TransferRequestFromJSONTyped(json, false);
}

export function TransferRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransferRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'toAccount': json['to_account'],
        'amount': json['amount'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function TransferRequestToJSON(json: any): TransferRequest {
    return TransferRequestToJSONTyped(json, false);
}

export function TransferRequestToJSONTyped(value?: TransferRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'to_account': value['toAccount'],
        'amount': value['amount'],
        'description': value['description'],
    };
}

