//
// BalanceResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct BalanceResponse: Codable, JSONEncodable, Hashable {

    public var accountId: UUID
    /** Balance formatted as string (decimal.Decimal.String()). */
    public var balance: String
    public var currency: String

    public init(accountId: UUID, balance: String, currency: String) {
        self.accountId = accountId
        self.balance = balance
        self.currency = currency
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case accountId = "account_id"
        case balance
        case currency
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(accountId, forKey: .accountId)
        try container.encode(balance, forKey: .balance)
        try container.encode(currency, forKey: .currency)
    }
}

