//
// CreateMovementRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateMovementRequest: Codable, JSONEncodable, Hashable {

    public enum ModelType: String, Codable, CaseIterable {
        case credit = "credit"
        case debit = "debit"
    }
    /** Decimal encoded as string (shopspring/decimal) */
    public var amount: String
    public var type: ModelType
    public var description: String?

    public init(amount: String, type: ModelType, description: String? = nil) {
        self.amount = amount
        self.type = type
        self.description = description
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case amount
        case type
        case description
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(amount, forKey: .amount)
        try container.encode(type, forKey: .type)
        try container.encodeIfPresent(description, forKey: .description)
    }
}

