//
// ModelErrorResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Current error envelope from &#x60;internal/util/errors.go&#x60;. Note: for non-*util.APIError errors, the server responds with code&#x3D;500 and message&#x3D;\&quot;internal server error\&quot;.  */
public struct ModelErrorResponse: Codable, JSONEncodable, Hashable {

    public var error: APIError

    public init(error: APIError) {
        self.error = error
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case error
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(error, forKey: .error)
    }
}

