//
// Movement.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Mirrors &#x60;internal/model.Movement&#x60; JSON. NOTE: in Go it serializes &#x60;amount&#x60; as decimal (shopspring/decimal) which is typically a JSON string/number depending on config. TODO: confirm runtime JSON encoding for decimal.Decimal and adjust if needed.  */
public struct Movement: Codable, JSONEncodable, Hashable {

    public enum ModelType: String, Codable, CaseIterable {
        case credit = "credit"
        case debit = "debit"
    }
    public var id: Int64
    public var accountId: UUID
    /** Decimal encoded as string (shopspring/decimal) */
    public var amount: String
    public var type: ModelType
    public var description: String
    public var occurredAt: Date

    public init(id: Int64, accountId: UUID, amount: String, type: ModelType, description: String, occurredAt: Date) {
        self.id = id
        self.accountId = accountId
        self.amount = amount
        self.type = type
        self.description = description
        self.occurredAt = occurredAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case accountId = "account_id"
        case amount
        case type
        case description
        case occurredAt = "occurred_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(accountId, forKey: .accountId)
        try container.encode(amount, forKey: .amount)
        try container.encode(type, forKey: .type)
        try container.encode(description, forKey: .description)
        try container.encode(occurredAt, forKey: .occurredAt)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension Movement: Identifiable {}
