//
// PaginationMeta.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PaginationMeta: Codable, JSONEncodable, Hashable {

    public var currentPage: Int
    public var totalPages: Int
    public var totalItems: Int
    public var perPage: Int

    public init(currentPage: Int, totalPages: Int, totalItems: Int, perPage: Int) {
        self.currentPage = currentPage
        self.totalPages = totalPages
        self.totalItems = totalItems
        self.perPage = perPage
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case currentPage = "current_page"
        case totalPages = "total_pages"
        case totalItems = "total_items"
        case perPage = "per_page"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(currentPage, forKey: .currentPage)
        try container.encode(totalPages, forKey: .totalPages)
        try container.encode(totalItems, forKey: .totalItems)
        try container.encode(perPage, forKey: .perPage)
    }
}

