//
// PaginatedTransfersResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Concrete shape of &#x60;util.PaginatedResponse&#x60; as returned by &#x60;TransferService.GetByAccountID()&#x60;.  */
public struct PaginatedTransfersResponse: Codable, JSONEncodable, Hashable {

    public var data: [Transfer]
    public var pagination: PaginationMeta

    public init(data: [Transfer], pagination: PaginationMeta) {
        self.data = data
        self.pagination = pagination
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case data
        case pagination
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(data, forKey: .data)
        try container.encode(pagination, forKey: .pagination)
    }
}

