//
// SignUpRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SignUpRequest: Codable, JSONEncodable, Hashable {

    public static let passwordRule = StringRule(minLength: 8, maxLength: nil, pattern: nil)
    public static let usernameRule = StringRule(minLength: 3, maxLength: nil, pattern: nil)
    public var email: String
    public var password: String
    public var username: String
    public var firstName: String
    public var lastName: String
    public var fiscalCode: String

    public init(email: String, password: String, username: String, firstName: String, lastName: String, fiscalCode: String) {
        self.email = email
        self.password = password
        self.username = username
        self.firstName = firstName
        self.lastName = lastName
        self.fiscalCode = fiscalCode
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case email
        case password
        case username
        case firstName = "first_name"
        case lastName = "last_name"
        case fiscalCode = "fiscal_code"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(email, forKey: .email)
        try container.encode(password, forKey: .password)
        try container.encode(username, forKey: .username)
        try container.encode(firstName, forKey: .firstName)
        try container.encode(lastName, forKey: .lastName)
        try container.encode(fiscalCode, forKey: .fiscalCode)
    }
}

