//
// Transfer.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Transfer: Codable, JSONEncodable, Hashable {

    public enum Status: String, Codable, CaseIterable {
        case pending = "pending"
        case completed = "completed"
        case failed = "failed"
    }
    public var id: Int64
    public var fromAccount: UUID
    public var toAccount: UUID
    /** Decimal encoded as string (shopspring/decimal) */
    public var amount: String
    public var status: Status
    public var initiatedAt: Date
    public var completedAt: Date?

    public init(id: Int64, fromAccount: UUID, toAccount: UUID, amount: String, status: Status, initiatedAt: Date, completedAt: Date?) {
        self.id = id
        self.fromAccount = fromAccount
        self.toAccount = toAccount
        self.amount = amount
        self.status = status
        self.initiatedAt = initiatedAt
        self.completedAt = completedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case fromAccount = "from_account"
        case toAccount = "to_account"
        case amount
        case status
        case initiatedAt = "initiated_at"
        case completedAt = "completed_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(fromAccount, forKey: .fromAccount)
        try container.encode(toAccount, forKey: .toAccount)
        try container.encode(amount, forKey: .amount)
        try container.encode(status, forKey: .status)
        try container.encode(initiatedAt, forKey: .initiatedAt)
        try container.encode(completedAt, forKey: .completedAt)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension Transfer: Identifiable {}
