//
// TransferRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TransferRequest: Codable, JSONEncodable, Hashable {

    public var toAccount: UUID
    /** Decimal encoded as string (shopspring/decimal) */
    public var amount: String
    public var description: String?

    public init(toAccount: UUID, amount: String, description: String? = nil) {
        self.toAccount = toAccount
        self.amount = amount
        self.description = description
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case toAccount = "to_account"
        case amount
        case description
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(toAccount, forKey: .toAccount)
        try container.encode(amount, forKey: .amount)
        try container.encodeIfPresent(description, forKey: .description)
    }
}

