// Code generated by MockGen. DO NOT EDIT.
// Source: VDM2-BankBE/internal/repository (interfaces: MovementRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	model "VDM2-BankBE/internal/model"
	util "VDM2-BankBE/internal/util"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockMovementRepository is a mock of MovementRepository interface.
type MockMovementRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMovementRepositoryMockRecorder
}

// MockMovementRepositoryMockRecorder is the mock recorder for MockMovementRepository.
type MockMovementRepositoryMockRecorder struct {
	mock *MockMovementRepository
}

// NewMockMovementRepository creates a new mock instance.
func NewMockMovementRepository(ctrl *gomock.Controller) *MockMovementRepository {
	mock := &MockMovementRepository{ctrl: ctrl}
	mock.recorder = &MockMovementRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMovementRepository) EXPECT() *MockMovementRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockMovementRepository) Create(arg0 context.Context, arg1 *model.Movement) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockMovementRepositoryMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockMovementRepository)(nil).Create), arg0, arg1)
}

// GetByAccountID mocks base method.
func (m *MockMovementRepository) GetByAccountID(arg0 context.Context, arg1 uuid.UUID, arg2 *util.PaginationParams) ([]*model.Movement, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByAccountID", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*model.Movement)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetByAccountID indicates an expected call of GetByAccountID.
func (mr *MockMovementRepositoryMockRecorder) GetByAccountID(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByAccountID", reflect.TypeOf((*MockMovementRepository)(nil).GetByAccountID), arg0, arg1, arg2)
}

// GetByID mocks base method.
func (m *MockMovementRepository) GetByID(arg0 context.Context, arg1 uint64) (*model.Movement, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", arg0, arg1)
	ret0, _ := ret[0].(*model.Movement)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockMovementRepositoryMockRecorder) GetByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockMovementRepository)(nil).GetByID), arg0, arg1)
}
