// Code generated by MockGen. DO NOT EDIT.
// Source: VDM2-BankBE/internal/repository (interfaces: OAuthTokenRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	model "VDM2-BankBE/internal/model"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockOAuthTokenRepository is a mock of OAuthTokenRepository interface.
type MockOAuthTokenRepository struct {
	ctrl     *gomock.Controller
	recorder *MockOAuthTokenRepositoryMockRecorder
}

// MockOAuthTokenRepositoryMockRecorder is the mock recorder for MockOAuthTokenRepository.
type MockOAuthTokenRepositoryMockRecorder struct {
	mock *MockOAuthTokenRepository
}

// NewMockOAuthTokenRepository creates a new mock instance.
func NewMockOAuthTokenRepository(ctrl *gomock.Controller) *MockOAuthTokenRepository {
	mock := &MockOAuthTokenRepository{ctrl: ctrl}
	mock.recorder = &MockOAuthTokenRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOAuthTokenRepository) EXPECT() *MockOAuthTokenRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockOAuthTokenRepository) Create(arg0 context.Context, arg1 *model.OAuthToken) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockOAuthTokenRepositoryMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockOAuthTokenRepository)(nil).Create), arg0, arg1)
}

// Delete mocks base method.
func (m *MockOAuthTokenRepository) Delete(arg0 context.Context, arg1 uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockOAuthTokenRepositoryMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockOAuthTokenRepository)(nil).Delete), arg0, arg1)
}

// GetByUserID mocks base method.
func (m *MockOAuthTokenRepository) GetByUserID(arg0 context.Context, arg1 uuid.UUID) (*model.OAuthToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserID", arg0, arg1)
	ret0, _ := ret[0].(*model.OAuthToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserID indicates an expected call of GetByUserID.
func (mr *MockOAuthTokenRepositoryMockRecorder) GetByUserID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserID", reflect.TypeOf((*MockOAuthTokenRepository)(nil).GetByUserID), arg0, arg1)
}

// Update mocks base method.
func (m *MockOAuthTokenRepository) Update(arg0 context.Context, arg1 *model.OAuthToken) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockOAuthTokenRepositoryMockRecorder) Update(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockOAuthTokenRepository)(nil).Update), arg0, arg1)
}
