// Code generated by MockGen. DO NOT EDIT.
// Source: VDM2-BankBE/internal/service (interfaces: MovementService)

// Package mocks is a generated GoMock package.
package mocks

import (
	model "VDM2-BankBE/internal/model"
	util "VDM2-BankBE/internal/util"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
	decimal "github.com/shopspring/decimal"
)

// MockMovementService is a mock of MovementService interface.
type MockMovementService struct {
	ctrl     *gomock.Controller
	recorder *MockMovementServiceMockRecorder
}

// MockMovementServiceMockRecorder is the mock recorder for MockMovementService.
type MockMovementServiceMockRecorder struct {
	mock *MockMovementService
}

// NewMockMovementService creates a new mock instance.
func NewMockMovementService(ctrl *gomock.Controller) *MockMovementService {
	mock := &MockMovementService{ctrl: ctrl}
	mock.recorder = &MockMovementServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMovementService) EXPECT() *MockMovementServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockMovementService) Create(arg0 context.Context, arg1 uuid.UUID, arg2 decimal.Decimal, arg3, arg4 string) (*model.Movement, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(*model.Movement)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockMovementServiceMockRecorder) Create(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockMovementService)(nil).Create), arg0, arg1, arg2, arg3, arg4)
}

// GetByAccountID mocks base method.
func (m *MockMovementService) GetByAccountID(arg0 context.Context, arg1 uuid.UUID, arg2, arg3 int) (*util.PaginatedResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByAccountID", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*util.PaginatedResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByAccountID indicates an expected call of GetByAccountID.
func (mr *MockMovementServiceMockRecorder) GetByAccountID(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByAccountID", reflect.TypeOf((*MockMovementService)(nil).GetByAccountID), arg0, arg1, arg2, arg3)
}

// GetByID mocks base method.
func (m *MockMovementService) GetByID(arg0 context.Context, arg1 uint64) (*model.Movement, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", arg0, arg1)
	ret0, _ := ret[0].(*model.Movement)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockMovementServiceMockRecorder) GetByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockMovementService)(nil).GetByID), arg0, arg1)
}
