// Code generated by MockGen. DO NOT EDIT.
// Source: VDM2-BankBE/internal/service (interfaces: CacheClient)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
	decimal "github.com/shopspring/decimal"
)

// MockCacheClient is a mock of CacheClient interface.
type MockCacheClient struct {
	ctrl     *gomock.Controller
	recorder *MockCacheClientMockRecorder
}

// MockCacheClientMockRecorder is the mock recorder for MockCacheClient.
type MockCacheClientMockRecorder struct {
	mock *MockCacheClient
}

// NewMockCacheClient creates a new mock instance.
func NewMockCacheClient(ctrl *gomock.Controller) *MockCacheClient {
	mock := &MockCacheClient{ctrl: ctrl}
	mock.recorder = &MockCacheClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCacheClient) EXPECT() *MockCacheClientMockRecorder {
	return m.recorder
}

// GetBalanceCache mocks base method.
func (m *MockCacheClient) GetBalanceCache(arg0 context.Context, arg1 uuid.UUID) (decimal.Decimal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBalanceCache", arg0, arg1)
	ret0, _ := ret[0].(decimal.Decimal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBalanceCache indicates an expected call of GetBalanceCache.
func (mr *MockCacheClientMockRecorder) GetBalanceCache(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalanceCache", reflect.TypeOf((*MockCacheClient)(nil).GetBalanceCache), arg0, arg1)
}

// GetOAuthState mocks base method.
func (m *MockCacheClient) GetOAuthState(arg0 context.Context, arg1 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOAuthState", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOAuthState indicates an expected call of GetOAuthState.
func (mr *MockCacheClientMockRecorder) GetOAuthState(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOAuthState", reflect.TypeOf((*MockCacheClient)(nil).GetOAuthState), arg0, arg1)
}

// SetBalanceCache mocks base method.
func (m *MockCacheClient) SetBalanceCache(arg0 context.Context, arg1 uuid.UUID, arg2 decimal.Decimal) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetBalanceCache", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetBalanceCache indicates an expected call of SetBalanceCache.
func (mr *MockCacheClientMockRecorder) SetBalanceCache(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetBalanceCache", reflect.TypeOf((*MockCacheClient)(nil).SetBalanceCache), arg0, arg1, arg2)
}

// SetOAuthState mocks base method.
func (m *MockCacheClient) SetOAuthState(arg0 context.Context, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetOAuthState", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetOAuthState indicates an expected call of SetOAuthState.
func (mr *MockCacheClientMockRecorder) SetOAuthState(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetOAuthState", reflect.TypeOf((*MockCacheClient)(nil).SetOAuthState), arg0, arg1, arg2)
}
