// Code generated by MockGen. DO NOT EDIT.
// Source: VDM2-BankBE/internal/service (interfaces: TransferService)

// Package mocks is a generated GoMock package.
package mocks

import (
	model "VDM2-BankBE/internal/model"
	util "VDM2-BankBE/internal/util"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
	decimal "github.com/shopspring/decimal"
)

// MockTransferService is a mock of TransferService interface.
type MockTransferService struct {
	ctrl     *gomock.Controller
	recorder *MockTransferServiceMockRecorder
}

// MockTransferServiceMockRecorder is the mock recorder for MockTransferService.
type MockTransferServiceMockRecorder struct {
	mock *MockTransferService
}

// NewMockTransferService creates a new mock instance.
func NewMockTransferService(ctrl *gomock.Controller) *MockTransferService {
	mock := &MockTransferService{ctrl: ctrl}
	mock.recorder = &MockTransferServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransferService) EXPECT() *MockTransferServiceMockRecorder {
	return m.recorder
}

// GetByAccountID mocks base method.
func (m *MockTransferService) GetByAccountID(arg0 context.Context, arg1 uuid.UUID, arg2, arg3 int) (*util.PaginatedResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByAccountID", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*util.PaginatedResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByAccountID indicates an expected call of GetByAccountID.
func (mr *MockTransferServiceMockRecorder) GetByAccountID(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByAccountID", reflect.TypeOf((*MockTransferService)(nil).GetByAccountID), arg0, arg1, arg2, arg3)
}

// GetByID mocks base method.
func (m *MockTransferService) GetByID(arg0 context.Context, arg1 uint64) (*model.Transfer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", arg0, arg1)
	ret0, _ := ret[0].(*model.Transfer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockTransferServiceMockRecorder) GetByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockTransferService)(nil).GetByID), arg0, arg1)
}

// Transfer mocks base method.
func (m *MockTransferService) Transfer(arg0 context.Context, arg1, arg2 uuid.UUID, arg3 decimal.Decimal, arg4 string) (*model.Transfer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Transfer", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(*model.Transfer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Transfer indicates an expected call of Transfer.
func (mr *MockTransferServiceMockRecorder) Transfer(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Transfer", reflect.TypeOf((*MockTransferService)(nil).Transfer), arg0, arg1, arg2, arg3, arg4)
}
