// Code generated by MockGen. DO NOT EDIT.
// Source: VDM2-BankBE/internal/service (interfaces: GoogleOAuthClient)

// Package mocks is a generated GoMock package.
package mocks

import (
	oauth "VDM2-BankBE/pkg/oauth"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	oauth2 "golang.org/x/oauth2"
)

// MockGoogleOAuthClient is a mock of GoogleOAuthClient interface.
type MockGoogleOAuthClient struct {
	ctrl     *gomock.Controller
	recorder *MockGoogleOAuthClientMockRecorder
}

// MockGoogleOAuthClientMockRecorder is the mock recorder for MockGoogleOAuthClient.
type MockGoogleOAuthClientMockRecorder struct {
	mock *MockGoogleOAuthClient
}

// NewMockGoogleOAuthClient creates a new mock instance.
func NewMockGoogleOAuthClient(ctrl *gomock.Controller) *MockGoogleOAuthClient {
	mock := &MockGoogleOAuthClient{ctrl: ctrl}
	mock.recorder = &MockGoogleOAuthClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGoogleOAuthClient) EXPECT() *MockGoogleOAuthClientMockRecorder {
	return m.recorder
}

// Exchange mocks base method.
func (m *MockGoogleOAuthClient) Exchange(arg0 context.Context, arg1 string) (*oauth2.Token, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exchange", arg0, arg1)
	ret0, _ := ret[0].(*oauth2.Token)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exchange indicates an expected call of Exchange.
func (mr *MockGoogleOAuthClientMockRecorder) Exchange(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exchange", reflect.TypeOf((*MockGoogleOAuthClient)(nil).Exchange), arg0, arg1)
}

// GetAuthURL mocks base method.
func (m *MockGoogleOAuthClient) GetAuthURL(arg0 string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAuthURL", arg0)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetAuthURL indicates an expected call of GetAuthURL.
func (mr *MockGoogleOAuthClientMockRecorder) GetAuthURL(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAuthURL", reflect.TypeOf((*MockGoogleOAuthClient)(nil).GetAuthURL), arg0)
}

// GetUserInfo mocks base method.
func (m *MockGoogleOAuthClient) GetUserInfo(arg0 context.Context, arg1 *oauth2.Token) (*oauth.GoogleUserInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserInfo", arg0, arg1)
	ret0, _ := ret[0].(*oauth.GoogleUserInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserInfo indicates an expected call of GetUserInfo.
func (mr *MockGoogleOAuthClientMockRecorder) GetUserInfo(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserInfo", reflect.TypeOf((*MockGoogleOAuthClient)(nil).GetUserInfo), arg0, arg1)
}
