// Code generated by MockGen. DO NOT EDIT.
// Source: VDM2-BankBE/internal/service (interfaces: TxDB)

// Package mocks is a generated GoMock package.
package mocks

import (
	sql "database/sql"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	gorm "gorm.io/gorm"
)

// MockTxDB is a mock of TxDB interface.
type MockTxDB struct {
	ctrl     *gomock.Controller
	recorder *MockTxDBMockRecorder
}

// MockTxDBMockRecorder is the mock recorder for MockTxDB.
type MockTxDBMockRecorder struct {
	mock *MockTxDB
}

// NewMockTxDB creates a new mock instance.
func NewMockTxDB(ctrl *gomock.Controller) *MockTxDB {
	mock := &MockTxDB{ctrl: ctrl}
	mock.recorder = &MockTxDBMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTxDB) EXPECT() *MockTxDBMockRecorder {
	return m.recorder
}

// Transaction mocks base method.
func (m *MockTxDB) Transaction(arg0 func(*gorm.DB) error, arg1 ...*sql.TxOptions) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Transaction", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Transaction indicates an expected call of Transaction.
func (mr *MockTxDBMockRecorder) Transaction(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Transaction", reflect.TypeOf((*MockTxDB)(nil).Transaction), varargs...)
}
