/* tslint:disable */
/* eslint-disable */
/**
 * VDM2 Banking API
 * Baseline OpenAPI spec extracted from the existing Gin router/handlers. After this initial extraction, this OpenAPI contract becomes the source of truth. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BalanceResponse,
  CreateMovementRequest,
  ErrorResponse,
  Movement,
  PaginatedMovementsResponse,
} from '../models/index';
import {
    BalanceResponseFromJSON,
    BalanceResponseToJSON,
    CreateMovementRequestFromJSON,
    CreateMovementRequestToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    MovementFromJSON,
    MovementToJSON,
    PaginatedMovementsResponseFromJSON,
    PaginatedMovementsResponseToJSON,
} from '../models/index';

export interface AccountsCreateMovementRequest {
    createMovementRequest: CreateMovementRequest;
}

export interface AccountsListMovementsRequest {
    page?: number;
    limit?: number;
}

/**
 * AccountsApi - interface
 * 
 * @export
 * @interface AccountsApiInterface
 */
export interface AccountsApiInterface {
    /**
     * 
     * @summary Create account movement
     * @param {CreateMovementRequest} createMovementRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccountsApiInterface
     */
    accountsCreateMovementRaw(requestParameters: AccountsCreateMovementRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Movement>>;

    /**
     * Create account movement
     */
    accountsCreateMovement(requestParameters: AccountsCreateMovementRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Movement>;

    /**
     * 
     * @summary Get account balance
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccountsApiInterface
     */
    accountsGetBalanceRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BalanceResponse>>;

    /**
     * Get account balance
     */
    accountsGetBalance(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BalanceResponse>;

    /**
     * 
     * @summary List account movements (paginated)
     * @param {number} [page] Page number (default: 1)
     * @param {number} [limit] Items per page (default: 10, max: 100)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccountsApiInterface
     */
    accountsListMovementsRaw(requestParameters: AccountsListMovementsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginatedMovementsResponse>>;

    /**
     * List account movements (paginated)
     */
    accountsListMovements(requestParameters: AccountsListMovementsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginatedMovementsResponse>;

}

/**
 * 
 */
export class AccountsApi extends runtime.BaseAPI implements AccountsApiInterface {

    /**
     * Create account movement
     */
    async accountsCreateMovementRaw(requestParameters: AccountsCreateMovementRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Movement>> {
        if (requestParameters['createMovementRequest'] == null) {
            throw new runtime.RequiredError(
                'createMovementRequest',
                'Required parameter "createMovementRequest" was null or undefined when calling accountsCreateMovement().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerPASETO", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerJWT", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/accounts/movements`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateMovementRequestToJSON(requestParameters['createMovementRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MovementFromJSON(jsonValue));
    }

    /**
     * Create account movement
     */
    async accountsCreateMovement(requestParameters: AccountsCreateMovementRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Movement> {
        const response = await this.accountsCreateMovementRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get account balance
     */
    async accountsGetBalanceRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BalanceResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerPASETO", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerJWT", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/accounts/balance`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BalanceResponseFromJSON(jsonValue));
    }

    /**
     * Get account balance
     */
    async accountsGetBalance(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BalanceResponse> {
        const response = await this.accountsGetBalanceRaw(initOverrides);
        return await response.value();
    }

    /**
     * List account movements (paginated)
     */
    async accountsListMovementsRaw(requestParameters: AccountsListMovementsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginatedMovementsResponse>> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerPASETO", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerJWT", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/accounts/movements`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginatedMovementsResponseFromJSON(jsonValue));
    }

    /**
     * List account movements (paginated)
     */
    async accountsListMovements(requestParameters: AccountsListMovementsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginatedMovementsResponse> {
        const response = await this.accountsListMovementsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
