/* tslint:disable */
/* eslint-disable */
/**
 * VDM2 Banking API
 * Baseline OpenAPI spec extracted from the existing Gin router/handlers. After this initial extraction, this OpenAPI contract becomes the source of truth. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorResponse,
  PaginatedTransfersResponse,
  Transfer,
  TransferRequest,
} from '../models/index';
import {
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    PaginatedTransfersResponseFromJSON,
    PaginatedTransfersResponseToJSON,
    TransferFromJSON,
    TransferToJSON,
    TransferRequestFromJSON,
    TransferRequestToJSON,
} from '../models/index';

export interface TransfersCreateRequest {
    transferRequest: TransferRequest;
}

export interface TransfersListRequest {
    page?: number;
    limit?: number;
}

/**
 * TransfersApi - interface
 * 
 * @export
 * @interface TransfersApiInterface
 */
export interface TransfersApiInterface {
    /**
     * 
     * @summary Create a transfer
     * @param {TransferRequest} transferRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TransfersApiInterface
     */
    transfersCreateRaw(requestParameters: TransfersCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Transfer>>;

    /**
     * Create a transfer
     */
    transfersCreate(requestParameters: TransfersCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Transfer>;

    /**
     * 
     * @summary List transfers (paginated)
     * @param {number} [page] Page number (default: 1)
     * @param {number} [limit] Items per page (default: 10, max: 100)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TransfersApiInterface
     */
    transfersListRaw(requestParameters: TransfersListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginatedTransfersResponse>>;

    /**
     * List transfers (paginated)
     */
    transfersList(requestParameters: TransfersListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginatedTransfersResponse>;

}

/**
 * 
 */
export class TransfersApi extends runtime.BaseAPI implements TransfersApiInterface {

    /**
     * Create a transfer
     */
    async transfersCreateRaw(requestParameters: TransfersCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Transfer>> {
        if (requestParameters['transferRequest'] == null) {
            throw new runtime.RequiredError(
                'transferRequest',
                'Required parameter "transferRequest" was null or undefined when calling transfersCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerPASETO", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerJWT", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/transfers`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TransferRequestToJSON(requestParameters['transferRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TransferFromJSON(jsonValue));
    }

    /**
     * Create a transfer
     */
    async transfersCreate(requestParameters: TransfersCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Transfer> {
        const response = await this.transfersCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List transfers (paginated)
     */
    async transfersListRaw(requestParameters: TransfersListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginatedTransfersResponse>> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerPASETO", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerJWT", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/transfers`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginatedTransfersResponseFromJSON(jsonValue));
    }

    /**
     * List transfers (paginated)
     */
    async transfersList(requestParameters: TransfersListRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginatedTransfersResponse> {
        const response = await this.transfersListRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
