PageParam:
  name: page
  in: query
  required: false
  schema:
    type: integer
    minimum: 1
    default: 1
  description: "Page number (default: 1)"

LimitParam:
  name: limit
  in: query
  required: false
  schema:
    type: integer
    minimum: 1
    maximum: 100
    default: 10
  description: "Items per page (default: 10, max: 100)"

OAuthCodeParam:
  name: code
  in: query
  required: true
  schema:
    type: string
  description: OAuth code

OAuthStateParam:
  name: state
  in: query
  required: true
  schema:
    type: string
  description: CSRF state

