/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.PaginatedMovementsResponse
import org.openapitools.client.models.Movement
import org.openapitools.client.models.PaginationMeta

class PaginatedMovementsResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PaginatedMovementsResponse
        //val modelInstance = PaginatedMovementsResponse()

        // to test the property ``data``
        should("test `data`") {
            // uncomment below to test the property
            //modelInstance.`data` shouldBe ("TODO")
        }

        // to test the property `pagination`
        should("test pagination") {
            // uncomment below to test the property
            //modelInstance.pagination shouldBe ("TODO")
        }

    }
}
