/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.PaginationMeta

class PaginationMetaTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PaginationMeta
        //val modelInstance = PaginationMeta()

        // to test the property `currentPage`
        should("test currentPage") {
            // uncomment below to test the property
            //modelInstance.currentPage shouldBe ("TODO")
        }

        // to test the property `totalPages`
        should("test totalPages") {
            // uncomment below to test the property
            //modelInstance.totalPages shouldBe ("TODO")
        }

        // to test the property `totalItems`
        should("test totalItems") {
            // uncomment below to test the property
            //modelInstance.totalItems shouldBe ("TODO")
        }

        // to test the property `perPage`
        should("test perPage") {
            // uncomment below to test the property
            //modelInstance.perPage shouldBe ("TODO")
        }

    }
}
