/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.Transfer

class TransferTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Transfer
        //val modelInstance = Transfer()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `fromAccount`
        should("test fromAccount") {
            // uncomment below to test the property
            //modelInstance.fromAccount shouldBe ("TODO")
        }

        // to test the property `toAccount`
        should("test toAccount") {
            // uncomment below to test the property
            //modelInstance.toAccount shouldBe ("TODO")
        }

        // to test the property `amount` - Decimal encoded as string (shopspring/decimal)
        should("test amount") {
            // uncomment below to test the property
            //modelInstance.amount shouldBe ("TODO")
        }

        // to test the property `status`
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property `initiatedAt`
        should("test initiatedAt") {
            // uncomment below to test the property
            //modelInstance.initiatedAt shouldBe ("TODO")
        }

        // to test the property `completedAt`
        should("test completedAt") {
            // uncomment below to test the property
            //modelInstance.completedAt shouldBe ("TODO")
        }

    }
}
