/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.TransferRequest

class TransferRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of TransferRequest
        //val modelInstance = TransferRequest()

        // to test the property `toAccount`
        should("test toAccount") {
            // uncomment below to test the property
            //modelInstance.toAccount shouldBe ("TODO")
        }

        // to test the property `amount` - Decimal encoded as string (shopspring/decimal)
        should("test amount") {
            // uncomment below to test the property
            //modelInstance.amount shouldBe ("TODO")
        }

        // to test the property `description`
        should("test description") {
            // uncomment below to test the property
            //modelInstance.description shouldBe ("TODO")
        }

    }
}
