/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.apis.AccountsApi
import org.openapitools.client.models.BalanceResponse
import org.openapitools.client.models.CreateMovementRequest
import org.openapitools.client.models.ErrorResponse
import org.openapitools.client.models.Movement
import org.openapitools.client.models.PaginatedMovementsResponse

class AccountsApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AccountsApi
        //val apiInstance = AccountsApi()

        // to test accountsCreateMovement
        should("test accountsCreateMovement") {
            // uncomment below to test accountsCreateMovement
            //val createMovementRequest : CreateMovementRequest =  // CreateMovementRequest | 
            //val result : Movement = apiInstance.accountsCreateMovement(createMovementRequest)
            //result shouldBe ("TODO")
        }

        // to test accountsGetBalance
        should("test accountsGetBalance") {
            // uncomment below to test accountsGetBalance
            //val result : BalanceResponse = apiInstance.accountsGetBalance()
            //result shouldBe ("TODO")
        }

        // to test accountsListMovements
        should("test accountsListMovements") {
            // uncomment below to test accountsListMovements
            //val page : kotlin.Int = 56 // kotlin.Int | Page number (default: 1)
            //val limit : kotlin.Int = 56 // kotlin.Int | Items per page (default: 10, max: 100)
            //val result : PaginatedMovementsResponse = apiInstance.accountsListMovements(page, limit)
            //result shouldBe ("TODO")
        }

    }
}
