/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.apis.AuthApi
import org.openapitools.client.models.AuthResponse
import org.openapitools.client.models.ErrorResponse
import org.openapitools.client.models.LoginRequest
import org.openapitools.client.models.SignUpRequest
import org.openapitools.client.models.User

class AuthApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AuthApi
        //val apiInstance = AuthApi()

        // to test authGoogle
        should("test authGoogle") {
            // uncomment below to test authGoogle
            //apiInstance.authGoogle()
        }

        // to test authGoogleCallback
        should("test authGoogleCallback") {
            // uncomment below to test authGoogleCallback
            //val code : kotlin.String = code_example // kotlin.String | OAuth code
            //val state : kotlin.String = state_example // kotlin.String | CSRF state
            //val result : kotlin.String = apiInstance.authGoogleCallback(code, state)
            //result shouldBe ("TODO")
        }

        // to test authLogin
        should("test authLogin") {
            // uncomment below to test authLogin
            //val loginRequest : LoginRequest =  // LoginRequest | 
            //val result : AuthResponse = apiInstance.authLogin(loginRequest)
            //result shouldBe ("TODO")
        }

        // to test authSignUp
        should("test authSignUp") {
            // uncomment below to test authSignUp
            //val signUpRequest : SignUpRequest =  // SignUpRequest | 
            //val result : User = apiInstance.authSignUp(signUpRequest)
            //result shouldBe ("TODO")
        }

    }
}
