/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.apis.MetaApi

class MetaApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of MetaApi
        //val apiInstance = MetaApi()

        // to test healthCheck
        should("test healthCheck") {
            // uncomment below to test healthCheck
            //apiInstance.healthCheck()
        }

        // to test metrics
        should("test metrics") {
            // uncomment below to test metrics
            //val result : kotlin.String = apiInstance.metrics()
            //result shouldBe ("TODO")
        }

        // to test swaggerUi
        should("test swaggerUi") {
            // uncomment below to test swaggerUi
            //val any : kotlin.String = any_example // kotlin.String | Wildcard path segment (Gin route uses /swagger/_*any)
            //val result : kotlin.String = apiInstance.swaggerUi(any)
            //result shouldBe ("TODO")
        }

    }
}
