/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.apis.TransfersApi
import org.openapitools.client.models.ErrorResponse
import org.openapitools.client.models.PaginatedTransfersResponse
import org.openapitools.client.models.Transfer
import org.openapitools.client.models.TransferRequest

class TransfersApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of TransfersApi
        //val apiInstance = TransfersApi()

        // to test transfersCreate
        should("test transfersCreate") {
            // uncomment below to test transfersCreate
            //val transferRequest : TransferRequest =  // TransferRequest | 
            //val result : Transfer = apiInstance.transfersCreate(transferRequest)
            //result shouldBe ("TODO")
        }

        // to test transfersList
        should("test transfersList") {
            // uncomment below to test transfersList
            //val page : kotlin.Int = 56 // kotlin.Int | Page number (default: 1)
            //val limit : kotlin.Int = 56 // kotlin.Int | Items per page (default: 10, max: 100)
            //val result : PaginatedTransfersResponse = apiInstance.transfersList(page, limit)
            //result shouldBe ("TODO")
        }

    }
}
