//
// AccountsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class AccountsAPI {

    /**
     Create account movement
     
     - parameter createMovementRequest: (body)  
     - returns: Movement
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func accountsCreateMovement(createMovementRequest: CreateMovementRequest) async throws -> Movement {
        return try await accountsCreateMovementWithRequestBuilder(createMovementRequest: createMovementRequest).execute().body
    }

    /**
     Create account movement
     - POST /api/v1/accounts/movements
     - Bearer Token:
       - type: http
       - name: BearerPASETO
     - Bearer Token:
       - type: http
       - name: BearerJWT
     - parameter createMovementRequest: (body)  
     - returns: RequestBuilder<Movement> 
     */
    open class func accountsCreateMovementWithRequestBuilder(createMovementRequest: CreateMovementRequest) -> RequestBuilder<Movement> {
        let localVariablePath = "/api/v1/accounts/movements"
        let localVariableURLString = VDM2BankSDKAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: createMovementRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Movement>.Type = VDM2BankSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get account balance
     
     - returns: BalanceResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func accountsGetBalance() async throws -> BalanceResponse {
        return try await accountsGetBalanceWithRequestBuilder().execute().body
    }

    /**
     Get account balance
     - GET /api/v1/accounts/balance
     - Bearer Token:
       - type: http
       - name: BearerPASETO
     - Bearer Token:
       - type: http
       - name: BearerJWT
     - returns: RequestBuilder<BalanceResponse> 
     */
    open class func accountsGetBalanceWithRequestBuilder() -> RequestBuilder<BalanceResponse> {
        let localVariablePath = "/api/v1/accounts/balance"
        let localVariableURLString = VDM2BankSDKAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<BalanceResponse>.Type = VDM2BankSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     List account movements (paginated)
     
     - parameter page: (query) Page number (default: 1) (optional, default to 1)
     - parameter limit: (query) Items per page (default: 10, max: 100) (optional, default to 10)
     - returns: PaginatedMovementsResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func accountsListMovements(page: Int? = nil, limit: Int? = nil) async throws -> PaginatedMovementsResponse {
        return try await accountsListMovementsWithRequestBuilder(page: page, limit: limit).execute().body
    }

    /**
     List account movements (paginated)
     - GET /api/v1/accounts/movements
     - Bearer Token:
       - type: http
       - name: BearerPASETO
     - Bearer Token:
       - type: http
       - name: BearerJWT
     - parameter page: (query) Page number (default: 1) (optional, default to 1)
     - parameter limit: (query) Items per page (default: 10, max: 100) (optional, default to 10)
     - returns: RequestBuilder<PaginatedMovementsResponse> 
     */
    open class func accountsListMovementsWithRequestBuilder(page: Int? = nil, limit: Int? = nil) -> RequestBuilder<PaginatedMovementsResponse> {
        let localVariablePath = "/api/v1/accounts/movements"
        let localVariableURLString = VDM2BankSDKAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "page": (wrappedValue: page?.encodeToJSON(), isExplode: true),
            "limit": (wrappedValue: limit?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<PaginatedMovementsResponse>.Type = VDM2BankSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
