//
// AuthAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class AuthAPI {

    /**
     Start Google OAuth flow
     
     - returns: Void
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func authGoogle() async throws {
        return try await authGoogleWithRequestBuilder().execute().body
    }

    /**
     Start Google OAuth flow
     - GET /api/v1/auth/google
     - Redirects the user-agent to Google and sets `oauth_state` cookie.
     - returns: RequestBuilder<Void> 
     */
    open class func authGoogleWithRequestBuilder() -> RequestBuilder<Void> {
        let localVariablePath = "/api/v1/auth/google"
        let localVariableURLString = VDM2BankSDKAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = VDM2BankSDKAPI.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Handle Google OAuth callback
     
     - parameter code: (query) OAuth code 
     - parameter state: (query) CSRF state 
     - returns: String
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func authGoogleCallback(code: String, state: String) async throws -> String {
        return try await authGoogleCallbackWithRequestBuilder(code: code, state: state).execute().body
    }

    /**
     Handle Google OAuth callback
     - GET /api/v1/auth/google/callback
     - parameter code: (query) OAuth code 
     - parameter state: (query) CSRF state 
     - returns: RequestBuilder<String> 
     */
    open class func authGoogleCallbackWithRequestBuilder(code: String, state: String) -> RequestBuilder<String> {
        let localVariablePath = "/api/v1/auth/google/callback"
        let localVariableURLString = VDM2BankSDKAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "code": (wrappedValue: code.encodeToJSON(), isExplode: true),
            "state": (wrappedValue: state.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<String>.Type = VDM2BankSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Login
     
     - parameter loginRequest: (body)  
     - returns: AuthResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func authLogin(loginRequest: LoginRequest) async throws -> AuthResponse {
        return try await authLoginWithRequestBuilder(loginRequest: loginRequest).execute().body
    }

    /**
     Login
     - POST /api/v1/auth/login
     - parameter loginRequest: (body)  
     - returns: RequestBuilder<AuthResponse> 
     */
    open class func authLoginWithRequestBuilder(loginRequest: LoginRequest) -> RequestBuilder<AuthResponse> {
        let localVariablePath = "/api/v1/auth/login"
        let localVariableURLString = VDM2BankSDKAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: loginRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AuthResponse>.Type = VDM2BankSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Register a new user
     
     - parameter signUpRequest: (body)  
     - returns: User
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func authSignUp(signUpRequest: SignUpRequest) async throws -> User {
        return try await authSignUpWithRequestBuilder(signUpRequest: signUpRequest).execute().body
    }

    /**
     Register a new user
     - POST /api/v1/auth/signup
     - parameter signUpRequest: (body)  
     - returns: RequestBuilder<User> 
     */
    open class func authSignUpWithRequestBuilder(signUpRequest: SignUpRequest) -> RequestBuilder<User> {
        let localVariablePath = "/api/v1/auth/signup"
        let localVariableURLString = VDM2BankSDKAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: signUpRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<User>.Type = VDM2BankSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }
}
