//
// TransfersAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class TransfersAPI {

    /**
     Create a transfer
     
     - parameter transferRequest: (body)  
     - returns: Transfer
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func transfersCreate(transferRequest: TransferRequest) async throws -> Transfer {
        return try await transfersCreateWithRequestBuilder(transferRequest: transferRequest).execute().body
    }

    /**
     Create a transfer
     - POST /api/v1/transfers
     - Bearer Token:
       - type: http
       - name: BearerPASETO
     - Bearer Token:
       - type: http
       - name: BearerJWT
     - parameter transferRequest: (body)  
     - returns: RequestBuilder<Transfer> 
     */
    open class func transfersCreateWithRequestBuilder(transferRequest: TransferRequest) -> RequestBuilder<Transfer> {
        let localVariablePath = "/api/v1/transfers"
        let localVariableURLString = VDM2BankSDKAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: transferRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Transfer>.Type = VDM2BankSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     List transfers (paginated)
     
     - parameter page: (query) Page number (default: 1) (optional, default to 1)
     - parameter limit: (query) Items per page (default: 10, max: 100) (optional, default to 10)
     - returns: PaginatedTransfersResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func transfersList(page: Int? = nil, limit: Int? = nil) async throws -> PaginatedTransfersResponse {
        return try await transfersListWithRequestBuilder(page: page, limit: limit).execute().body
    }

    /**
     List transfers (paginated)
     - GET /api/v1/transfers
     - Bearer Token:
       - type: http
       - name: BearerPASETO
     - Bearer Token:
       - type: http
       - name: BearerJWT
     - parameter page: (query) Page number (default: 1) (optional, default to 1)
     - parameter limit: (query) Items per page (default: 10, max: 100) (optional, default to 10)
     - returns: RequestBuilder<PaginatedTransfersResponse> 
     */
    open class func transfersListWithRequestBuilder(page: Int? = nil, limit: Int? = nil) -> RequestBuilder<PaginatedTransfersResponse> {
        let localVariablePath = "/api/v1/transfers"
        let localVariableURLString = VDM2BankSDKAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "page": (wrappedValue: page?.encodeToJSON(), isExplode: true),
            "limit": (wrappedValue: limit?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<PaginatedTransfersResponse>.Type = VDM2BankSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
